// Embed the skills/*/SKILL.md files into src/generated/skills.ts so that
// `ep skills install` works from both the npm package and the standalone binary.
// Run automatically before build (prebuild) and the exe builds.
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const SKILLS_DIR = "skills";
const OUT_DIR = "src/generated";
const OUT = join(OUT_DIR, "skills.ts");

const files = [];
function walk(dir, base) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    const rel = base ? `${base}/${entry.name}` : entry.name;
    if (entry.isDirectory()) walk(full, rel);
    else if (entry.name === "SKILL.md") files.push({ path: rel, content: readFileSync(full, "utf8") });
  }
}
if (existsSync(SKILLS_DIR)) walk(SKILLS_DIR, "");

mkdirSync(OUT_DIR, { recursive: true });
const body =
  "// AUTO-GENERATED by scripts/generate-skills.mjs — do not edit by hand.\n" +
  "export interface SkillFile { path: string; content: string; }\n" +
  `export const SKILL_FILES: SkillFile[] = ${JSON.stringify(files, null, 2)};\n`;
writeFileSync(OUT, body);
process.stderr.write(`generated ${OUT} with ${files.length} skill file(s)\n`);
